### ISSUE TITLE
Failed Installation

### ISSUE THREAD

**Issue by dongilbert** [beberlei/license-manager#16]
Is there something I need to do in addition to the steps listed in order to install? I run it in app_dev.php and get an Sql Exception, so I checked the database, and the tables aren't created, the database is empty.

**Comment by dongilbert** [comment]
For any coming upon this later, the easiest way is to install the Doctrine Migration Bundle (as explained here: http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html) and then add it to your AppKernel.php `$bundles` array. Then, run `app/console doctrine:migrations:diff; app/console doctrine:migrations:migrate;` to install the table schema.

**Comment by beberlei** [comment]
@dongilbert i will be working on making this project a free service in the next days, if you don't mind waiting a little :)

**Comment by dongilbert** [comment]
That's good to hear. I was able to get it set up, so no worries.

**Comment by lsmith77** [comment]
sweet :)
